package com.org.dms.dao.service.reportForms;

import com.org.dms.common.DicConstant;
import com.org.framework.base.BaseDAO;
import com.org.framework.common.BaseResultSet;
import com.org.framework.common.PageManager;
import com.org.framework.common.QuerySet;
import com.org.framework.common.User;
import com.org.mvc.context.ActionContext;

public class ServiceCostClassingReportDao extends BaseDAO {
	// 定义instance
	public static final ServiceCostClassingReportDao getInstance(ActionContext atx) {
		ServiceCostClassingReportDao dao = new ServiceCostClassingReportDao();
		atx.setDBFactory(dao.factory);
		return dao;
	}

	/**
	 * @throws Exception
	 *             设定文件
	 * @return BaseResultSet 返回类型
	 */
	public BaseResultSet search(PageManager page, User user, String conditions)
			throws Exception {
		// 定义返回结果集
		BaseResultSet bs = null;
		StringBuffer sql= new StringBuffer();
		sql.append("select name, A1, A2,A3,A4,A5,A6,A7,A8,A9, A1+ A2+A3+A4+A5+A6+A7+A8+A9 A10\n" );
		sql.append("  from (select '材料档（家）' name,\n" );
		sql.append("\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 0 AND sumCost <= 5000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A1,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 5000 AND sumCost < =10000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A2,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 10000 AND sumCost <= 20000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A3,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >20000 AND sumCost <= 40000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A4,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >40000 AND sumCost <= 80000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A5,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >80000 AND sumCost <= 160000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A6,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >160000 AND sumCost < =320000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A7,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >320000 AND sumCost < 640000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A8,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >640000  THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A9\n" );
		sql.append("\n" );
		sql.append("          from (SELECT T.ORG_CODE,\n" );
		sql.append("\n" );
		sql.append("               T.SUMMARY sumCost\n" );
		sql.append("          FROM SE_BU_CLAIM_SETTLE T\n" );
		sql.append("         WHERE T.SETTLE_TYPE = '304602' AND\n" );
		sql.append(conditions );
		sql.append("         )\n" );
		sql.append("        union\n" );
		sql.append("\n" );
		sql.append("        select '材料费（元）' name,\n" );
		sql.append("\n" );
		sql.append("                sum(CASE\n" );
		sql.append("                     WHEN sumCost > 0 AND sumCost <= 5000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A1,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 5000 AND sumCost < =10000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A2,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 10000 AND sumCost <= 20000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A3,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >20000 AND sumCost <= 40000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A4,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >40000 AND sumCost <= 80000 THEN\n" );
		sql.append("                     sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A5,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >80000 AND sumCost <= 160000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A6,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >160000 AND sumCost < =320000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A7,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >320000 AND sumCost < 640000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A8,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >640000  THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A9\n" );
		sql.append("\n" );
		sql.append("          from (SELECT T.ORG_CODE,\n" );
		sql.append("\n" );
		sql.append("               T.SUMMARY sumCost\n" );
		sql.append("          FROM SE_BU_CLAIM_SETTLE T\n" );
		sql.append("         WHERE T.SETTLE_TYPE = '304602' AND\n" );
		sql.append(conditions );
		sql.append("          )\n" );
		sql.append("\n" );
		sql.append("                 union\n" );
		sql.append("\n" );
		sql.append("                 select '总费用（家）' name,\n" );
		sql.append("\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 0 AND sumCost <= 5000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A1,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 5000 AND sumCost < =10000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A2,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 10000 AND sumCost <= 20000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A3,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >20000 AND sumCost <= 40000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A4,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >40000 AND sumCost <= 80000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A5,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >80000 AND sumCost <= 160000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A6,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >160000 AND sumCost < =320000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A7,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >320000 AND sumCost < 640000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A8,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >640000  THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A9\n" );
		sql.append("\n" );
		sql.append("          from (select ORG_CODE, sum(SUMMARY)  sumCost\n" );
		sql.append("          FROM (SELECT T.ORG_CODE,\n" );
		sql.append("\n" );
		sql.append("                       T.SUMMARY,\n" );
		sql.append("                       T.SETTLE_TYPE\n" );
		sql.append("                  FROM SE_BU_CLAIM_SETTLE T WHERE\n" );
		sql.append(conditions );
		sql.append("                   )\n" );
		sql.append("         group by ORG_CODE)\n" );
		sql.append("        union\n" );
		sql.append("\n" );
		sql.append("        select '总费用（元）' name,\n" );
		sql.append("\n" );
		sql.append("                sum(CASE\n" );
		sql.append("                     WHEN sumCost > 0 AND sumCost <= 5000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A1,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 5000 AND sumCost < =10000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A2,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 10000 AND sumCost <= 20000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A3,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >20000 AND sumCost <= 40000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A4,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >40000 AND sumCost <= 80000 THEN\n" );
		sql.append("                     sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A5,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >80000 AND sumCost <= 160000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A6,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >160000 AND sumCost < =320000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A7,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >320000 AND sumCost < 640000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A8,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >640000  THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A9\n" );
		sql.append("\n" );
		sql.append("          from (select ORG_CODE, sum(SUMMARY)  sumCost\n" );
		sql.append("          FROM (SELECT T.ORG_CODE,\n" );
		sql.append("\n" );
		sql.append("                       T.SUMMARY,\n" );
		sql.append("                       T.SETTLE_TYPE\n" );
		sql.append("                  FROM SE_BU_CLAIM_SETTLE T WHERE\n" );
		sql.append(conditions );
		sql.append("                   )\n" );
		sql.append("         group by ORG_CODE)\n" );
		sql.append("         )\n" );
		sql.append(" order by name");		

		// 执行方法，不需要传递conn参数
		bs = factory.select(sql.toString(), page);
		return bs;
	}

	public QuerySet download(String conditions) throws Exception {

		StringBuffer sql = new StringBuffer();
		sql.append("SELECT  ROWNUM,T.* FROM(");
		sql.append("select name, A1, A2,A3,A4,A5,A6,A7,A8,A9, A1+ A2+A3+A4+A5+A6+A7+A8+A9 A10\n" );
		sql.append("  from (select '材料档（家）' name,\n" );
		sql.append("\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 0 AND sumCost <= 5000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A1,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 5000 AND sumCost < =10000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A2,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 10000 AND sumCost <= 20000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A3,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >20000 AND sumCost <= 40000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A4,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >40000 AND sumCost <= 80000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A5,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >80000 AND sumCost <= 160000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A6,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >160000 AND sumCost < =320000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A7,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >320000 AND sumCost < 640000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A8,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >640000  THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A9\n" );
		sql.append("\n" );
		sql.append("          from (SELECT T.ORG_CODE,\n" );
		sql.append("\n" );
		sql.append("               T.SUMMARY sumCost\n" );
		sql.append("          FROM SE_BU_CLAIM_SETTLE T\n" );
		sql.append("         WHERE T.SETTLE_TYPE = '304602' AND\n" );
		sql.append(conditions );
		sql.append("         )\n" );
		sql.append("        union\n" );
		sql.append("\n" );
		sql.append("        select '材料费（元）' name,\n" );
		sql.append("\n" );
		sql.append("                sum(CASE\n" );
		sql.append("                     WHEN sumCost > 0 AND sumCost <= 5000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A1,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 5000 AND sumCost < =10000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A2,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 10000 AND sumCost <= 20000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A3,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >20000 AND sumCost <= 40000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A4,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >40000 AND sumCost <= 80000 THEN\n" );
		sql.append("                     sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A5,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >80000 AND sumCost <= 160000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A6,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >160000 AND sumCost < =320000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A7,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >320000 AND sumCost < 640000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A8,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >640000  THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A9\n" );
		sql.append("\n" );
		sql.append("          from (SELECT T.ORG_CODE,\n" );
		sql.append("\n" );
		sql.append("               T.SUMMARY sumCost\n" );
		sql.append("          FROM SE_BU_CLAIM_SETTLE T\n" );
		sql.append("         WHERE T.SETTLE_TYPE = '304602' AND\n" );
		sql.append(conditions );
		sql.append("          )\n" );
		sql.append("\n" );
		sql.append("                 union\n" );
		sql.append("\n" );
		sql.append("                 select '总费用（家）' name,\n" );
		sql.append("\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 0 AND sumCost <= 5000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A1,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 5000 AND sumCost < =10000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A2,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 10000 AND sumCost <= 20000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A3,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >20000 AND sumCost <= 40000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A4,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >40000 AND sumCost <= 80000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A5,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >80000 AND sumCost <= 160000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A6,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >160000 AND sumCost < =320000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A7,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >320000 AND sumCost < 640000 THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A8,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >640000  THEN\n" );
		sql.append("                      1\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A9\n" );
		sql.append("\n" );
		sql.append("          from (select ORG_CODE, sum(SUMMARY)  sumCost\n" );
		sql.append("          FROM (SELECT T.ORG_CODE,\n" );
		sql.append("\n" );
		sql.append("                       T.SUMMARY,\n" );
		sql.append("                       T.SETTLE_TYPE\n" );
		sql.append("                  FROM SE_BU_CLAIM_SETTLE T WHERE\n" );
		sql.append(conditions );
		sql.append("                   )\n" );
		sql.append("         group by ORG_CODE)\n" );
		sql.append("        union\n" );
		sql.append("\n" );
		sql.append("        select '总费用（元）' name,\n" );
		sql.append("\n" );
		sql.append("                sum(CASE\n" );
		sql.append("                     WHEN sumCost > 0 AND sumCost <= 5000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A1,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 5000 AND sumCost < =10000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A2,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost > 10000 AND sumCost <= 20000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A3,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >20000 AND sumCost <= 40000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A4,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >40000 AND sumCost <= 80000 THEN\n" );
		sql.append("                     sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A5,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >80000 AND sumCost <= 160000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A6,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >160000 AND sumCost < =320000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A7,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >320000 AND sumCost < 640000 THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A8,\n" );
		sql.append("               sum(CASE\n" );
		sql.append("                     WHEN sumCost >640000  THEN\n" );
		sql.append("                      sumCost\n" );
		sql.append("                     ELSE\n" );
		sql.append("                      0\n" );
		sql.append("                   END) A9\n" );
		sql.append("\n" );
		sql.append("          from (select ORG_CODE, sum(SUMMARY)  sumCost\n" );
		sql.append("          FROM (SELECT T.ORG_CODE,\n" );
		sql.append("\n" );
		sql.append("                       T.SUMMARY,\n" );
		sql.append("                       T.SETTLE_TYPE\n" );
		sql.append("                  FROM SE_BU_CLAIM_SETTLE T WHERE\n" );
		sql.append(conditions );
		sql.append("                   )\n" );
		sql.append("         group by ORG_CODE)\n" );
		sql.append("         )\n" );
		sql.append(" order by name");		

		sql.append("    ) T ORDER BY ROWNUM");
		// 执行方法，不需要传递conn参数
		return factory.select(null, sql.toString());
	}
}
